### ISSUE TITLE
npm 引入uv-ui组件库报错

### ISSUE THREAD

**Issue by zhengcaifeng** [monsterxwx/uv-ui#1]
1、npm install uv-ui -S

2、在main文件中引入
<img width="325" alt="image" src="https://github.com/monsterxwx/uv-ui/assets/27950890/fc0f4419-8929-4a25-acd3-cdfba7f2bf90">

3、启动项目报错
[plugin:vite:import-analysis] Failed to resolve entry for package "uv-ui". The package may have incorrect main/module/exports specified in its package.json.
<img width="325" alt="image" src="https://github.com/monsterxwx/uv-ui/assets/27950890/1edaa212-9884-4be3-828f-fc4329d353a6">

**Comment by monsterxwx** [comment]
不好意思，好久没测试了，应该是打包后主文件的路径没找到，所以所有组件都没有导出，现在1.0.25的版本已经修复了

**Comment by monsterxwx** [comment]
另外样式的路径有修改，是这个路径：import 'uv-ui/es/style.css'
